### ISSUE TITLE
POST support for keys API (tracking)

### ISSUE THREAD

**Issue by marcparadise** [chef/chef-server#110]
The following related PRs are up for review: 

- [x] https://github.com/chef/enterprise-chef-server-schema/pull/26
- [x] https://github.com/chef/oc_erchef/pull/97
- [x] https://github.com/chef/chef-pedant/pull/101
- [x] https://github.com/chef/oc-chef-pedant/pull/93
- [x] https://github.com/chef/opscode-omnibus/pull/708 (placeholders pending final merges) 

ping @chef/lob

**Comment by sdelano** [comment]
Is there a commit to opscode-omnibus that pulls all of these in and has a migration to deploy the new schema?

**Comment by marcparadise** [comment]
I'll link it, it's just pending final version #s

**Comment by marcparadise** [comment]
Updated description with the omnibus PR

**Comment by marcparadise** [comment]
Reviewed and merged for Chef Server 12.0.5
