### ISSUE TITLE
Minor issue tracking (chef_secrets conversion)

### ISSUE THREAD

**Issue by marcparadise** [chef/chef-server#1108]
Done
====
- [x] chef-mover (mp: https://github.com/chef/chef-server/pull/1122)
- [x] oc-id: uses template oc_id.secret_token.rb.erb and populates it as OpscodeWebui::Application.config.secret_token = '<%= @cookie_secret %>'
- [x] data_collector token (mp: https://github.com/chef/chef-server/pull/1131)
- [x] /etc/opscode-analytics data written by actions.rb recipe contains secrets (mp: https://github.com/chef/chef-server/pull/1132) 
- [x] private-chef::rabbitmq (setting credentials) also makes partybus use veil (https://github.com/chef/chef-server/pull/1123)
- [x] external rabbitmq (https://github.com/chef/chef-server/pull/1128)
- [x] user secret ingestion (https://github.com/chef/chef-server/pull/1121)
- [x] opscode-expander (using env, needs to be converted to veil: https://github.com/chef/chef-server/tree/ssd%2Fexpander-to-veil)
- [x] oc_id to use veil (ssd+sr: https://github.com/chef/chef-server/pull/1116)
- [x] redis password rendered into lua configuration (In progress https://github.com/chef/chef-server/pull/1113)
- [x] Finish moving keys into secrets file (with migration strategy)
- [x] Pedant to veil (PR winding down)
- [x] redis patch to use environment
- [x] wrapper to launch redis with correct environment (https://github.com/chef/chef-server/pull/1110)
- [x] Q: what's the final decision on where we keep the key?: _For the initial release, this will be a set location (/etc/opscode). 

Descoped
========
- [ ] ~config item: key & data store location~

**Comment by srenatus** [comment]
> oc-id: uses template oc_id.secret_token.rb.erb and populates it

[Does it?](https://github.com/chef/chef-server/search?utf8=%E2%9C%93&q=secret_token.erb)
I think it uses [`oc_id.secret_token.rb`](https://github.com/chef/chef-server/blob/master/omnibus/files/private-chef-cookbooks/private-chef/templates/default/oc_id.secret_token.rb), and [`secret_token.erb`](https://github.com/chef/chef-server/blob/master/omnibus/files/private-chef-cookbooks/private-chef/templates/default/secret_token.erb) is just an unused leftover.
